### Importing all relevant libraries

In [1]:
import pandas as pd
import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

### Reading in both training and testing data sets

In [2]:
df = pd.read_csv('../data/train.csv',index_col='Id')
test = pd.read_csv('../data/test.csv',index_col='Id')
print('Training Data shape:',df.shape,'Testing Data shape:',test.shape)

Training Data shape: (2051, 80) Testing Data shape: (879, 79)

# Exploratory Data Analysis

In [3]:
df.head()

,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,Utilities,...,Screen Porch,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,
109,533352170,60,RL,NaN,13517,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,3,2010,WD,130500
544,531379050,60,RL,43.0,11492,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2009,WD,220000
153,535304180,20,RL,68.0,7922,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,1,2010,WD,109000
318,916386060,60,RL,73.0,9802,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2010,WD,174000
255,906425045,50,RL,82.0,14235,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,3,2010,WD,138500

In [4]:
df.describe().T.head()

,count,mean,std,min,25%,50%,75%,max
PID,2051.0,7.135900e+08,1.886918e+08,526301100.0,528458140.0,535453200.0,907180080.0,924152030.0
MS SubClass,2051.0,5.700878e+01,4.282422e+01,20.0,20.0,50.0,70.0,190.0
Lot Frontage,1721.0,6.905520e+01,2.326065e+01,21.0,58.0,68.0,80.0,313.0
Lot Area,2051.0,1.006521e+04,6.742489e+03,1300.0,7500.0,9430.0,11513.5,159000.0
Overall Qual,2051.0,6.112140e+00,1.426271e+00,1.0,5.0,6.0,7.0,10.0

In [5]:
df.sort_values(by="SalePrice")

,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,Utilities,...,Screen Porch,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,
182,902207130,30,RM,68.0,9656,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,12789
1554,910251050,20,A (agr),80.0,14584,Pave,NaN,Reg,Low,AllPub,...,0,0,NaN,NaN,NaN,0,2,2008,WD,13100
727,902477120,30,C (all),60.0,7879,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,GdWo,NaN,0,11,2009,WD,34900
2844,909101330,30,RL,60.0,8088,Pave,Grvl,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,2,2006,ConLD,35000
2881,911175430,20,C (all),50.0,9000,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,10,2006,WD,35311
710,902205030,50,RM,50.0,5925,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,GdWo,NaN,0,5,2009,WD,37900
1902,534450090,20,RL,50.0,5000,Pave,NaN,Reg,Low,AllPub,...,0,0,NaN,NaN,NaN,0,1,2007,WD,39300
1556,911102170,70,C (all),50.0,8500,Pave,Pave,Reg,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,7,2008,WD,40000
728,902477130,30,C (all),72.0,9392,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,9,2009,WD,44000
709,902205010,30,RM,50.0,5925,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,10,2009,WD,45000
2044,903484080,50,RM,60.0,10320,Pave,Grvl,Reg,Lvl,AllPub,...,84,0,NaN,NaN,NaN,0,9,2007,COD,50000
308,911204100,30,C (all),66.0,8712,Grvl,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,50138
2880,911175410,30,C (all),69.0,12366,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,10,2006,WD,51689
1221,534451170,30,RL,56.0,4130,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,7,2008,WD,52000
2690,903430130,30,RM,153.0,4118,Pave,Grvl,IR1,Bnk,AllPub,...,0,0,NaN,NaN,NaN,0,3,2006,WD,52500
1547,910202050,30,RM,40.0,3636,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,1,2008,WD,55000
207,903454060,190,RM,70.0,5600,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,Othr,3500,7,2010,WD,55000
307,911204090,20,C (all),66.0,8712,Grvl,NaN,Reg,Bnk,AllPub,...,0,0,NaN,NaN,Shed,54,6,2010,WD,55993
946,912251110,30,I (all),109.0,21780,Grvl,NaN,Reg,Lvl,NoSewr,...,0,0,NaN,NaN,NaN,0,3,2009,ConLD,57625
908,909175080,30,RL,60.0,8400,Pave,NaN,Reg,Bnk,AllPub,...,0,0,NaN,NaN,NaN,0,1,2009,WD,60000
791,905451340,20,RL,68.0,9571,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2009,COD,60000
766,904301375,30,RL,NaN,10020,Pave,NaN,IR1,Low,AllPub,...,0,0,NaN,NaN,NaN,0,3,2009,WD,61000
2654,902206020,30,RM,52.0,7830,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2006,WD,61500
562,532378120,20,RL,60.0,8281,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,GdWo,NaN,0,12,2009,WD,62383
754,903430070,90,RM,50.0,3000,Pave,Grvl,Reg,Bnk,AllPub,...,0,0,NaN,NaN,NaN,0,9,2009,WD,62500
768,904351240,50,RL,60.0,9780,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,3,2009,WD,63000
781,905228050,20,RL,NaN,9000,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2009,WD,63900
278,908102300,50,RL,89.0,11792,Pave,NaN,Reg,Lvl,AllPub,...,160,0,NaN,NaN,NaN,0,6,2010,WD,64000
2657,902207110,30,RM,48.0,5747,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2006,WD,64000
1903,534450110,20,RL,50.0,5000,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,4,2007,WD,64500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1773,528366050,20,RL,NaN,12692,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,5,2007,WD,430000
2337,527216050,60,RL,66.0,13682,Pave,NaN,IR2,HLS,AllPub,...,0,0,NaN,NaN,NaN,0,10,2006,New,438780
1700,528114050,20,RL,110.0,14977,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,7,2007,New,440000
1642,527256030,20,RL,85.0,14082,Pave,NaN,IR1,HLS,AllPub,...,0,0,NaN,NaN,NaN,0,1,2007,WD,441929
449,528166090,20,RL,110.0,15274,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,7,2009,WD,445000
1054,528104080,60,RL,67.0,14948,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,11,2008,New,446261
1694,528106110,20,RL,105.0,15431,Pave,NaN,Reg,Lvl,AllPub,...,175,0,NaN,NaN,NaN,0,8,2007,WD,450000
432,528110010,60,RL,97.0,13478,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2009,ConLI,451950
1643,527256040,20,RL,81.0,13870,Pave,NaN,IR1,HLS,AllPub,...,174,0,NaN,NaN,NaN,0,10,2007,New,455000
2330,527210030,60,RL,59.0,16023,Pave,NaN,IR1,HLS,AllPub,...,0,0,NaN,NaN,NaN,0,3,2006,New,457347
1060,528118090,60,RL,96.0,12539,Pave,NaN,Reg,Lvl,AllPub,...,192,0,NaN,NaN,NaN,0,6,2008,WD,460000
2383,528110050,20,RL,107.0,13891,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,9,2006,New,465000
1764,528327060,20,RL,NaN,11400,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,3,2007,WD,466500
514,528441090,20,RL,85.0,11128,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,GdPrv,NaN,0,10,2009,WD,468000
1426,906412010,20,RL,91.0,11778,Pave,NaN,Reg,Lvl,AllPub,...,255,0,NaN,NaN,NaN,0,6,2008,WD,475000
2667,902400110,75,RM,90.0,22950,Pave,NaN,IR2,Lvl,AllPub,...,410,0,NaN,GdPrv,NaN,0,6,2006,WD,475000
423,528104070,60,RL,104.0,13518,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,7,2009,New,485000
47,528176010,20,RL,110.0,14300,Pave,NaN,Reg,HLS,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,500000
1702,528118050,20,RL,59.0,17169,Pave,NaN,IR2,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,8,2007,New,500067
367,527214050,20,RL,63.0,17423,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,7,2009,New,501837
2335,527214060,60,RL,82.0,16052,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,7,2006,New,535000
16,527216070,60,RL,47.0,53504,Pave,NaN,IR2,HLS,AllPub,...,210,0,NaN,NaN,NaN,0,6,2010,WD,538000
2331,527210040,60,RL,60.0,18062,Pave,NaN,IR1,HLS,AllPub,...,0,0,NaN,NaN,NaN,0,9,2006,New,545224
457,528176030,20,RL,100.0,14836,Pave,NaN,IR1,HLS,AllPub,...,0,0,NaN,NaN,NaN,0,2,2009,WD,552000
424,528106020,20,RL,105.0,15431,Pave,NaN,Reg,Lvl,AllPub,...,170,0,NaN,NaN,NaN,0,4,2009,WD,555000
2333,527212030,60,RL,85.0,16056,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,7,2006,New,556581
434,528110090,60,RL,107.0,13891,Pave,NaN,Reg,Lvl,AllPub,...,192,0,NaN,NaN,NaN,0,1,2009,New,582933
2451,528360050,60,RL,114.0,17242,Pave,NaN,IR1,Lvl,AllPub,...,210,0,NaN,NaN,NaN,0,5,2006,WD,584500
1638,527216080,20,RL,52.0,51974,Pave,NaN,IR1,Lvl,AllPub,...,322,0,NaN,NaN,NaN,0,6,2007,New,591587
45,528150070,20,RL,100.0,12919,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,3,2010,New,611657

In [6]:
def box_func(df, ylabel):
    data = df.select_dtypes(include="object")
    fig, ax = plt.subplots(ncols = 1, nrows = data.shape[1], figsize = (8,data.shape[1]*6))
    i=0
    for col in data:
        sns.boxplot(x = ylabel, y = col, data = df,orient='h',ax=ax[i])
        i+=1
    plt.tight_layout()
#box_func(df,"SalePrice")

In [7]:
def scatter(df,target):
    data = df.select_dtypes(exclude="object")
    fig, ax = plt.subplots(ncols = 1, nrows = data.shape[1], figsize = (7,data.shape[1]*3))
    i = 0
    for col in data:
        sns.regplot(x = df[col],y = df[target],fit_reg=False, ax=ax[i])
        i += 1
        plt.tight_layout()
#scatter(df,"SalePrice")

# Data Cleaning

In [8]:
fill_na={'Lot Frontage':np.mean(df['Lot Frontage']),
         'Alley':'No Alley',
         'Mas Vnr Type':'No Vnr',
         'Mas Vnr Area':0,
         'Bsmt Qual':'No Bsmt',
         'Bsmt Cond':'No Bsmt',
         'Bsmt Exposure':'No Bsmt',
         'BsmtFin Type 1':'No Bsmt',
         'BsmtFin SF 1':0,
         'BsmtFin Type 2':'No Bsmt',
         'BsmtFin SF 2':0,
         'Bsmt Unf SF':0,
         'Total Bsmt SF':0,
         'Bsmt Full Bath':0,
         'Bsmt Half Bath':0,
         'Fireplace Qu':'No Fire',
         'Garage Type':'No Garage',
         'Garage Yr Blt':0,
         'Garage Qual':'No Garage',
         'Garage Cond':'No Garage',
         'Garage Finish':"No Garage",
         'Garage Cars':0,
         'Garage Area':0,
         'Pool QC':'No Pool',
         'Fence':'No Fence',
         'Misc Feature':'No Feature',
         'Electrical':'Mix'
        }

#### Additional Feature Engineering

In [9]:
df.fillna(value = fill_na,inplace = True)
test.fillna(fill_na,inplace=True)
df["Total Area"] = df["Total Bsmt SF"] + df["Gr Liv Area"] + df['Garage Area']
test['Total Area'] = test["Total Bsmt SF"] + test['Gr Liv Area'] + test["Garage Area"]

In [10]:
print("There are",df.isnull().sum().sum(),"null values in our training data frame")
print("There are",test.isnull().sum().sum(),"null values in our testing data frame")

There are 0 null values in our training data frame
There are 0 null values in our testing data frame

#### dropping outliers/incorrect values

In [11]:
df.drop(df[df['Lot Area']>100000].index,inplace=True)
df.drop(df[df['Garage Yr Blt']>2018].index,inplace=True)
df.drop(df[df['Total Area']>10000].index,inplace=True)
df.drop(df[df['SalePrice']<20000].index,inplace = True)

In [12]:
df.to_csv("../data/clean_data")
test.to_csv("../data/clean_test_data")